/* act.c */
extern fn_obj fn_by_long_name(str_str_fn *table, char *long_name);
extern void table_act(str_str_fn *table, Object *obj, char *long_name);
extern char *long_name(str_str_fn *table, char *name);
extern int act_debug(Object *obj, char *name);
extern void debug_quit(Object *obj);
extern void debug_fly(Object *obj);
extern void debug_put_wall(Object *obj);
extern void debug_put_space(Object *obj);
extern void debug_load_world(Object *obj);
extern void debug_save_world(Object *obj);
extern void debug_fps_plus(Object *obj);
extern void debug_fps_minus(Object *obj);
extern void debug_loot(Object *obj);
extern void debug_interactive_new_cell(Object *obj);
extern int act_skill(Object *obj, char *name);
extern int act_item(Object *obj, char *name);
extern void act(Object *obj, char *mode, int num);
/* debug_fn.c */
extern int msgbox(Object *o);
extern int msgbox2(Object *o);
extern int msgbox_yes_no(Object *o);
extern int fn_obj_damage(Object *o);
/* draw.c */
extern void set_notice(Object *obj, char *notice);
extern void gotoxy(int x, int y);
extern void set_color(char bg, char fg);
extern void print_notice(Object *obj, int x, int y);
extern void set_cell(CHAR_INFO *buffer, char c, int x, int y, unsigned char bg, unsigned char fg);
extern void set_str(CHAR_INFO *buffer, char *str, int x, int y, unsigned char bg, unsigned char fg);
extern void write_scr(CHAR_INFO *buffer, int cx, int cy);
extern void draw(World *w);
extern void draw_system(World *w);
extern void draw_fps(void);
extern void draw_map(World *w);
extern int draw_examine(int display_x, int display_y, World *w, int x, int y, Object *exclude);
extern void print_gauge(int x, int y, int max, int current, unsigned char bright_color, unsigned char dark_color);
extern void print_mode_name(int x, int y, Object *obj, char *mode);
extern void print_mode(int x, int y, Object *obj);
extern void print_mode_slots(int x, int y, Object *obj, int max_str_len, char (*slots)[32]);
/* global.c */
extern CHAR_INFO screen_buffer[24][80];
extern int goal_fps;
extern int frame_count;
extern state_slot table_state[100];
extern str_str_fn table_debug[100];
extern str_str_fn key_fn_table[100];
extern str_str_fn table_tick_obj_fn[100];
extern str_str_fn table_overlap_obj_fn[100];
extern fn_scene scene;
/* key_process.c */
extern void key_quit(Object *obj);
extern char *key_name(int key);
extern void table_key_process(str_str_fn *table, Object *obj);
extern void key_process(World *w);
extern void key_debug(Object *obj);
extern void key_move_up(Object *obj);
extern void key_move_down(Object *obj);
extern void key_move_left(Object *obj);
extern void key_move_right(Object *obj);
extern void key_attack(Object *obj);
extern void key_loot(Object *obj);
extern void key_skill_mode(Object *obj);
extern void key_item_mode(Object *obj);
extern void key_debug_mode(Object *obj);
extern void key_shortcut_0(Object *obj);
extern void key_shortcut_1(Object *obj);
extern void key_shortcut_2(Object *obj);
extern void key_shortcut_3(Object *obj);
extern void key_shortcut_4(Object *obj);
extern void key_shortcut_5(Object *obj);
extern void key_shortcut_6(Object *obj);
extern void key_shortcut_7(Object *obj);
extern void key_shortcut_8(Object *obj);
extern void key_shortcut_9(Object *obj);
/* main.c */
extern void game_over_update(World *w);
extern void scene_game_over(World *w);
extern World *game_init(void);
extern void tick_sleep(void);
extern void game_update(World *w);
extern void scene_map(World *w);
extern int main(void);
/* mk_obj.c */
extern fn_obj table_obj_fn_by_long_name(str_str_fn *table, char *long_name);
extern Object mk_dummy(World *w, int x, int y, Object *parent);
extern int char_pos_ith(char *buf, char c, int i);
extern char *get_line(char *buf, int i);
extern int str_len_char(char *str, char c);
extern int same_until_char(char *s1, char *s2, char c);
extern int set_obj_with_line(Object *o, char *line);
extern int mod_obj_with_buf(char *buf, Object *o);
extern Object *new_mk_obj(char *name, World *w, int x, int y, Object *parent);
/* obj_func.c */
extern int find_empty_slot(Object *obj, char *mode);
extern int num_of_empty_slot(Object *obj, char (*slots)[32]);
extern state_slot *find_slot(state_slot *table, char *name);
extern int empty_state_slot_index(Object *o);
extern int set_state(Object *o, state_slot *table, char *name);
extern int obj_move(World *w, Object *o, int ox, int oy);
extern int object_to_index(Object *obj);
extern int reverse_find_valid_obj_index(World *w);
extern void delete_object(Object *obj);
extern void delete_object_with_index(World *w, int index);
/* obj_handler_overlap.c */
extern int fn_heal(Object *me, Object *other);
extern int fn_damage(Object *me, Object *other);
extern int fn_kill(Object *me, Object *other);
extern int fn_loot_me(Object *me, Object *other);
extern int fn_explode_bullet(Object *me, Object *other);
/* obj_handler_tick.c */
extern int fn_heal_timer(Object *o);
extern int fn_do_rand(Object *o);
extern int fn_fire_timer(Object *o);
extern int fn_bomb_timer(Object *o);
extern int fn_death_drop(Object *me);
extern int fn_thru_bullet_timer(Object *me);
/* tick.c */
extern void tick_overlap(World *w);
extern int state_tick(Object *o);
extern void __OLD_tick_overlap(World *w);
extern void tick_self(World *w);
extern void tick(World *w);
/* world.c */
extern Object *obj_at(World *w, int x, int y, Object *exclude);
extern Cell *get_cell_layer(World *w, int x, int y, int layer);
extern int add_slot(Object *obj, char *mode, char *new_slot);
extern int save_world(World *w, char *file_name);
extern int load_world(World *w, char *file_name);
extern int put_cell(World *w, int x, int y, Cell c);
extern Cell interactive_new_cell(void);
extern Cell new_cell(char ch, int bg, int fg, int layer, int block);
extern int delete_cell(World *w, int x, int y);
extern int get_empty_obj_index(World *w);
extern int check_block(World *w, int x, int y, int layer);
